classDiagram

    class BetSide
    class Bet
    class Odds
    class MarketOdds
    class KellyBetScaler
    class BetStrategy
    class ValueBetStrategy
    class PosteriorResult
    class PredictionResult
    class Outcome
    class Score
    class Game
    class AttackDefenseSkill
    class GeneralSkill
    class ModelState
    class TrueskillAdapter
    class GameEngine
    class TrueskillBasicAdapter
    class TrueskillAdvancedAdapter
    class TrueskillAdvancedAttackDefenseAdapter
    class TrueSkillModelBasic
    class TrueSkillBasicGibbsSampling
    class TrueSkillBasicMessagePassing
    class TrueskillAdvancedAttackDefense
    class TrueskillAdvanced
    class NormalDistribution
